name: Apply Terraform

on:
  push:
    branches:
      - main

jobs:
  apply-terraform:
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    env:
      BACKEND_STORE_NAME: ${{ secrets.BACKEND_STORE_NAME }}
      PARAMETER_STORE_NAME: ${{ secrets.PARAMETER_STORE_NAME }}

    steps:
      - name: Notify Slack (start)
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#439FE0",
                  "pretext": "🚀 Build started",
                  "fields": [
                    {
                      "title": "Repo",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
          author_name: haramsong
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get backend configuration from SSM Parameter Store
        run: |
          aws ssm get-parameter \
            --name $BACKEND_STORE_NAME \
            --query Parameter.Value \
            --output text > state.config

      - name: Initialize Terraform
        run: |
          terraform init -backend-config=state.config

      - name: Get terraform configuration from SSM Parameter Store
        run: |
          aws ssm get-parameter \
            --name $PARAMETER_STORE_NAME \
            --query Parameter.Value \
            --output text > terraform.tfvars

      - name: Apply Terraform
        run: |
          terraform apply --auto-approve -no-color > apply.log 2>&1

      - name: Notify Slack (result)
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: haramsong
          fields: repo,workflow,job,took
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: Upload apply.log to Slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          path: apply.log
          channel: "#deployment-alarm"
